# roles/ansible-role-vault_profile/tasks/main.yaml
- name: Creating Vault profile.d
  ansible.builtin.template:
    src: vault_cluster.sh.j2
    dest: '/etc/profile.d/vault_cluster.sh'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: vault_enable_bash_profile == true

- name: Creating Vault log directory
  ansible.builtin.file:
    state: directory
    path: '{{ vault_log_dir }}'
    owner: '{{ vault_user }}'
    group: '{{ vault_group }}'
    mode: '0750'

- name: Creating Vault logrotate config
  ansible.builtin.template:
    src: logrotate_vault.conf.j2
    dest: vault_logrotate_config_filepath
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Debug
  ansible.builtin.debug:
    var: disable_tls

- name: Installing Vault CA cert to system
  ansible.builtin.copy:
    remote_src: yes
    src: '/opt/vault/tls/ca.crt'
    dest: '/usr/share/ca-certificates/vault_ca.pem'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when:
    - disable_tls == false
    - vault_system_vault_ca_cert == true
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  notify: Update Debian system certs

- name: Installing Vault CA cert to system
  ansible.builtin.copy:
    remote_src: yes
    src: '/opt/vault/tls/ca.crt'
    dest: '/etc/pki/ca-trust/source/anchors/vault_ca.pem'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when:
    - disable_tls == false
    - vault_system_vault_ca_cert == true
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  notify: Update RHEL system certs
